# Generated by Django 6.1.1 on 2026-09-16 13:20

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0037_auto_20210125_1833"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(max_length=50, verbose_name="имя заказчика"),
                ),
                (
                    "lastname",
                    models.CharField(max_length=50, verbose_name="фамилия заказчика"),
                ),
                (
                    "address",
                    models.CharField(max_length=100, verbose_name="адрес заказчика"),
                ),
                (
                    "phonenumber",
                    phonenumber_field.modelfields.PhoneNumberField(
                        db_index=True,
                        max_length=128,
                        region=None,
                        verbose_name="контактный номер заказчика",
                    ),
                ),
            ],
            options={
                "verbose_name": "оформленный заказ",
                "verbose_name_plural": "оформленные заказы",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="количество",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="foodcartapp.order",
                        verbose_name="заказ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="foodcartapp.product",
                        verbose_name="единица продукта",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар в заказе",
                "verbose_name_plural": "товары в заказе",
            },
        ),
    ]
