# Generated by Django 6.1.1 on 2026-09-16 16:07

from django.db import migrations


def set_item_prices(apps, schema_editor):
    OrderItem = apps.get_model("foodcartapp", "OrderItem")
    items = OrderItem.objects.select_related("product").iterator()
    for item in items:
        item.price = item.product.price
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0039_orderitem_price"),
    ]

    operations = [
        migrations.RunPython(set_item_prices, migrations.RunPython.noop),
    ]
