# Generated by Django 6.1.1 on 2026-09-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0042_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Принят"),
                    ("COOKING", "Готовится"),
                    ("DELIVERING", "У курьера"),
                    ("COMPLETED", "Доставлен"),
                ],
                db_index=True,
                default="CREATED",
                max_length=15,
                verbose_name="статус",
            ),
        ),
    ]
