# Generated by Django 6.1.1 on 2026-09-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0043_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="comment",
            field=models.TextField(blank=True, verbose_name="комментарий"),
        ),
    ]
