# Generated by Django 6.1.1 on 2026-09-16 18:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0044_order_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="called_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="время звонка менеджера"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="время принятия заказа",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="время доставки"
            ),
        ),
    ]
