# Generated by Django 6.1.1 on 2026-09-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0045_order_called_at_order_created_at_order_delivered_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("CASH", "Наличные"), ("CARD", "Безнал")],
                db_index=True,
                default="CASH",
                max_length=15,
                verbose_name="способ оплаты",
            ),
        ),
    ]
