# Generated by Django 6.1.1 on 2026-09-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0048_order_restaurant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=100, unique=True, verbose_name="адрес"),
                ),
                (
                    "lat",
                    models.FloatField(blank=True, null=True, verbose_name="широта"),
                ),
                (
                    "lon",
                    models.FloatField(blank=True, null=True, verbose_name="долгота"),
                ),
            ],
            options={
                "verbose_name": "адрес",
                "verbose_name_plural": "адреса",
            },
        ),
    ]
