# Generated by Django 6.1.1 on 2026-09-24 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0049_address"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("CASH", "Наличные"), ("CARD", "Безнал")],
                max_length=15,
                verbose_name="способ оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Принят"),
                    ("COOKING", "Готовится"),
                    ("DELIVERING", "У курьера"),
                    ("COMPLETED", "Доставлен"),
                    ("CANCELLED", "Отменён"),
                ],
                db_index=True,
                default="CREATED",
                max_length=15,
                verbose_name="статус",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="foodcartapp.product",
                verbose_name="товар",
            ),
        ),
    ]
