# Generated by Django 6.1.1 on 2026-09-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0050_delete_address_alter_order_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="called_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="время звонка менеджера",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="время доставки"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("CASH", "Наличные"), ("CARD", "Безнал")],
                db_index=True,
                max_length=15,
                verbose_name="способ оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Не обработан"),
                    ("COOKING", "Готовится"),
                    ("DELIVERING", "У курьера"),
                    ("COMPLETED", "Доставлен"),
                    ("CANCELLED", "Отменён"),
                ],
                db_index=True,
                default="CREATED",
                max_length=15,
                verbose_name="статус",
            ),
        ),
    ]
